Repository zilliztech/knowhere, pull requests merged in 2023-08, with the labels that each got.

#3 Split common/index.cc from knowhere/index.h
  include/knowhere/index.h
  src/common/index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm

#1 Support ScaNN index
  include/knowhere/comp/index_param.h
  src/common/config.cc
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_get_vector.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
  thirdparty/faiss/faiss/IndexIVFPQFastScan.h
  thirdparty/faiss/faiss/IndexScaNN.cpp
  thirdparty/faiss/faiss/IndexScaNN.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/impl/pq4_fast_scan.h
  thirdparty/faiss/faiss/impl/pq4_fast_scan_search_qbs.cpp
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
Labels: dco-passed, ci-passed, kind/improvement, lgtm

#4 Alpha-Candidates: Improve the performance when filtering search.
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, approved, size/S, lgtm

#8 Fix mac llvm compile
  thirdparty/faiss/faiss/impl/pq4_fast_scan_search_qbs.cpp
Labels: dco-passed, do-not-merge/missing-related-issue, approved, lgtm, size/XS

#2 Fix cosine bruteforce
  src/common/comp/brute_force.cc
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: dco-passed, kind/improvement, approved, lgtm, size/L

#7 Refine DiskANN AIO Parameters
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
  tests/ut/test_knowhere_init.cc
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
  thirdparty/DiskANN/include/diskann/aux_utils.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, approved, size/M, lgtm

#14 Add exact num for metric enum for compatibility
  thirdparty/faiss/faiss/MetricType.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#11 Copy and normalize query data when cosine for thread safe
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/common/utils.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#15 split build, search thread pool
  include/knowhere/comp/thread_pool.h
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  thirdparty/DiskANN/include/diskann/index.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/linux_aligned_file_reader.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/L

#13 Support search topk metric
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XS

#19 Decrease knowhere threads scheduling priority
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#22 Correctly log error message when failed to set thread priority
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, size/S

#20 Return the error message while failed to search with DiskANN
  include/knowhere/expected.h
  src/common/comp/brute_force.cc
  src/common/index.cc
  src/common/metric.h
  src/common/raft_metric.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cuh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/L

#23 Update install_deps.sh to fix release build error
  scripts/install_deps.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#21 Optimize IVFFLAT without codes
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#26 Temporary solution to fix ivf_flat search result wrong when cosine
  src/index/ivf/ivf.cc
Labels: approved, size/S

#24 change default stream size
  src/common/raft/raft_utils.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS

#36 Temporary solution to fix ivf_flat search result wrong when cosine
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#28 [skip e2e] delete release build on centos7
  .github/workflows/release.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#34 Remove libunwind in conanfile
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#32 add search latency metrics for grafana
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#42 Sync behavior of SUBSTRUCTURE/SUPERSTRUCTURE with 1.x
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/utils/binary_distances.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm
