Repository zilliztech/knowhere, pull requests merged in 2023-09, with the labels that each got.

#41 [skip e2e] update merge rule
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#51 [skip e2e]update mergify rule for non gpu code change
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#45 Fix scann add_with_ids logic
  thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#54 Remove code that lowers knowhere threads' priority
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#43 Optimize MemoryIOReader & MemoryIOWriter
  benchmark/hdf5/benchmark_hdf5.h
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/io/file_io.h
  src/io/memory_io.cc
  src/io/memory_io.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#56 populate and advise random access pattern
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#39 Remove IVF_FLAT_NM
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/ivf/ivf.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/Index.cpp
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.h
  thirdparty/faiss/faiss/gpu/GpuCloner.cpp
  thirdparty/faiss/faiss/gpu/GpuCloner.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFFlat.h
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.cu
  thirdparty/faiss/faiss/gpu/GpuIndexIVFScalarQuantizer.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/index_io.h
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XXL

#63 Add comments for accumulative alpha
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#60 IVFFLAT support get vector with metric cosine
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/common/utils.cc
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
  tests/ut/test_search.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XL

#64 Fix typo in comments
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#55 Remove out dated files
  .devcontainer.json
  .env
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#68 Populate the mapping only if MAP_POPULATE is defined
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#62 minor refactor: extract codes to search for top layers into a method
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#71 fix search on out-of-range id
  include/knowhere/bitsetview.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#76 New solution to handle IVF_FLAT backward compatibility
  src/common/utils.cc
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/index_io.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#77 ScaNN support with_raw_data build option
  include/knowhere/comp/index_param.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_get_vector.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/IndexRefine.h
  thirdparty/faiss/faiss/IndexScaNN.cpp
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#74 refactor hnsw search path
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/neighbor.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#84 Remove un-necessary faiss distance APIs
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#75 Add iterator support to HNSW index
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  tests/ut/test_iterator.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#85 Add missing header
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#83 multi cuda gpu support
  CMakeLists.txt
  src/common/raft/raft_utils.cc
  src/common/raft/raft_utils.h
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  src/index/ivf_raft/ivf_raft_config.h
  tests/ut/test_gpu_search.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#66 support rtx 30 series gpu
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#91 update cmake
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#72 changes needed for clang-16 to be working
  conanfile.py
  include/knowhere/bitsetview.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#98 [Cherry-pick] Fix DiskANN LRU Set Invalid Medoid
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#38 add version support
  .gitignore
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/comp/index_param.h
  include/knowhere/comp/knowhere_config.h
  include/knowhere/comp/local_file_manager.h
  include/knowhere/config.h
  include/knowhere/expected.h
  include/knowhere/factory.h
  include/knowhere/index.h
  include/knowhere/utils.h
  include/knowhere/version.h
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  src/common/comp/knowhere_config.cc
  src/common/config.cc
  src/common/factory.cc
  src/common/utils.cc
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/python/test_diskann.py
  tests/python/test_index_load_and_save.py
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
  tests/ut/test_utils.cc
  tests/ut/utils.h
Labels: dco-passed, do-not-merge/missing-related-issue, approved, size/XL

#80 Support faiss FLAT index get vector with metric COSINE
  src/common/comp/brute_force.cc
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexFlat.cpp
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexFlatCodes.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#102 Make sure scann 'm' build param larger than 0
  src/index/ivf/ivf.cc
Labels: dco-passed, approved, lgtm, size/XS, kind/bug

#93 Support IVF_FLAT backward compatible when cosine
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/config.h
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.cpp
  thirdparty/faiss/faiss/invlists/InvertedLists.h
Labels: kind/enhancement, dco-passed, approved, size/M, lgtm

#89 Fix clang-16 build of unit tests in debug mode
  tests/ut/CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#95 Add flat index util
  include/knowhere/utils.h
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#104 Add missing return keyword...
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#105 [improvement] Fix gpu index version
  src/index/cagra/cagra.cu
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_gpu_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#112 Change knowhere version format
  CMakeLists.txt
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  cmake/libs/libdiskann.cmake
  conanfile.py
  include/knowhere/comp/index_param.h
  include/knowhere/factory.h
  include/knowhere/utils.h
  include/knowhere/version.h
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  src/common/factory.cc
  src/common/utils.cc
  src/index/cagra/cagra.cu
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  tests/python/test_diskann.py
  tests/python/test_index_load_and_save.py
  tests/python/test_index_random.py
  tests/python/test_index_with_random.py
  tests/python/test_index_with_sift.py
  tests/ut/test_utils.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#111 Write old format IVF_FLAT index for backward compatible
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/index_node.h
  include/knowhere/utils.h
  include/knowhere/version.h
  src/common/utils.cc
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/index_io.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#87 Add clang-format and clang-tidy to precommit
  .pre-commit-config.yaml
  README.md
  scripts/prepare_clang_tidy.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#114 Construct IndexScaNN explicitly when deserialization
  thirdparty/faiss/faiss/impl/index_read.cpp
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#118 Fix clang asan warning
  tests/ut/test_get_vector.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#119 Add name prefix to all threads in knowhere thread pools
  include/knowhere/comp/thread_pool.h
  src/common/index_node_thread_pool_wrapper.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#121 lower the OS scheduling priority of knowhere threads
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#120 Use thread pool build hnsw
  src/index/hnsw/hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#127 Fix ut fail for version 0
  tests/ut/test_search.cc
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#124 Add size() function in diskann index
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, do-not-merge/missing-related-issue, approved, size/M, lgtm

#126 Update hnsw Size() function
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/visited_list_pool.h
Labels: dco-passed, kind/improvement, approved, size/S, lgtm

#129 Revert "lower the OS scheduling priority of knowhere threads"
  include/knowhere/comp/thread_pool.h
Labels: approved, size/S

#130 Readd Thread prioritization
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm
