Repository zilliztech/knowhere, pull requests merged in 2023-11, with the labels that each got.

#167 Improve IVF index mmap performance by cache policy
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#168 revert kw thread prio modify in v1.3.18
  .github/workflows/ut.yaml
  thirdparty/ctpl/ctpl-std.h
Labels: dco-passed, ci-passed, approved, size/S, lgtm

#170 Add new interface for brute force search and simd test in pyknowhere
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#180 Remove unused stats in PQFastScan
  thirdparty/faiss/faiss/IndexIVFPQFastScan.h
  thirdparty/faiss/faiss/IndexPQFastScan.cpp
  thirdparty/faiss/faiss/IndexPQFastScan.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#182 Upgrade conan to 1.61.0
  README.md
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  scripts/install_deps.sh
  scripts/python_deps.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#106 More fixes for clang-16 compiler
  CMakeLists.txt
  benchmark/CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#184 [2.2] Remove unused stats in PQFastScan (#180)
  thirdparty/faiss/faiss/IndexIVFPQFastScan.h
  thirdparty/faiss/faiss/IndexPQFastScan.cpp
  thirdparty/faiss/faiss/IndexPQFastScan.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#185 Add row number constraint for building scann index
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#174 Remove deprecated conan generator
  .github/workflows/analyzer.yaml
  CMakeLists.txt
  cmake/libs/libdiskann.cmake
  conanfile.py
  python/setup.py
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#194 Move read/writeBinaryPOD from hnswlib to knowhere utils.
  include/knowhere/utils.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#169 Remove diskann pramaters check in diskann.cc
  src/index/diskann/diskann.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#197 enhance: [skip e2e]update e2e-gpu builder image
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#195 Fix a jaccard distance problem that was causing #192
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexFlat.cpp
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#198 check cmake version
  ci/E2E.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#203 Add gen_fbin_file.cpp in benchmark
  benchmark/CMakeLists.txt
  benchmark/benchmark_base.h
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_hdf5.h
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/gen_fbin_file.cpp
  benchmark/hdf5/gen_hdf5_file.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#202 Refactor cached_beam_search to reduce duplicate code
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#204 Remove code for building DiskANN in windows/bing_infra.
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/aio_context_pool.h
  thirdparty/DiskANN/include/diskann/aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/ann_exception.h
  thirdparty/DiskANN/include/diskann/aux_utils.h
  thirdparty/DiskANN/include/diskann/distance.h
  thirdparty/DiskANN/include/diskann/index.h
  thirdparty/DiskANN/include/diskann/linux_aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/logger.h
  thirdparty/DiskANN/include/diskann/logger_impl.h
  thirdparty/DiskANN/include/diskann/memory_mapper.h
  thirdparty/DiskANN/include/diskann/partition_and_pq.h
  thirdparty/DiskANN/include/diskann/percentile_stats.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/include/diskann/simd_utils.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/include/diskann/windows_aligned_file_reader.h
  thirdparty/DiskANN/include/diskann/windows_customizations.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/dll/CMakeLists.txt
  thirdparty/DiskANN/src/dll/dllmain.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/logger.cpp
  thirdparty/DiskANN/src/memory_mapper.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/windows_aligned_file_reader.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#189 Add iterator support to pyknowhere interface.
  python/knowhere/knowhere.i
  python/setup.py
  src/common/config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#191 Generate diskann cache asynchronously.
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/include/semaphore.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: approved, size/L

#209 improve ScalarQuantizer performance, ESPECIALLY on old GCC
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
  thirdparty/faiss/faiss/impl/platform_macros.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#212 Update diskann range search param max_k to MAX_INT
  src/index/diskann/diskann_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#211 Update gen_fbin_file.cpp to support binary data type
  benchmark/hdf5/gen_fbin_file.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#207 Cagra support & update raft version
  CMakeLists.txt
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_knowhere.h
  cmake/libs/libraft.cmake
  cmake/libs/librapids.cmake
  include/knowhere/comp/index_param.h
  include/knowhere/comp/knowhere_config.h
  include/knowhere/device_bitset.h
  src/common/comp/knowhere_config.cc
  src/common/raft/integration/cagra_index.cu
  src/common/raft/integration/ivf_flat_index.cu
  src/common/raft/integration/ivf_pq_index.cu
  src/common/raft/integration/raft_initialization.cc
  src/common/raft/integration/raft_initialization.hpp
  src/common/raft/integration/raft_knowhere_config.hpp
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/integration/raft_knowhere_index.hpp
  src/common/raft/proto/raft_index.cuh
  src/common/raft/proto/raft_index_kind.hpp
  src/common/raft/raft.cu
  src/common/raft/raft_utils.cc
  src/common/raft/raft_utils.h
  src/index/cagra/cagra.cu
  src/index/cagra/cagra_config.h
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
  src/index/ivf_raft/ivf_raft.cu
  src/index/ivf_raft/ivf_raft.cuh
  tests/ut/test_gpu_search.cc
Labels: dco-passed, ci-passed, approved, lgtm, kind/feature, size/XXL

#219 Switch to brute force for hnsw when topk is super large
  tests/ut/test_iterator.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#221 Update HNSW build param M's valid range
  src/index/hnsw/hnsw_config.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#225 flush ids if use bitset filter
  src/common/raft/integration/raft_knowhere_index.cuh
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#226 Add async thread pool for generating diskann cache and catch unexpected return.
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: approved, size/L

#233 fix faiss arm neon hamming
  thirdparty/faiss/faiss/utils/hamming_distance/neon-inl.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#234 Change async thread pool size to 1
  knowhere/index/vector_index/IndexDiskANN.cpp
Labels: kind/improvement, approved, size/S, lgtm

#235 Add some log for diskann prepare
  knowhere/index/vector_index/IndexDiskANN.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: ci-passed, kind/improvement, approved, lgtm, size/XS

#230 Merge commits from Faiss baseline
  thirdparty/faiss/.circleci/config.yml
  thirdparty/faiss/benchs/bench_all_ivf/bench_all_ivf.py
  thirdparty/faiss/benchs/bench_fw/__init__.py
  thirdparty/faiss/benchs/bench_fw/benchmark.py
  thirdparty/faiss/benchs/bench_fw/benchmark_io.py
  thirdparty/faiss/benchs/bench_fw/descriptors.py
  thirdparty/faiss/benchs/bench_hybrid_cpu_gpu.py
  thirdparty/faiss/conda/faiss-gpu-raft/meta.yaml
  thirdparty/faiss/conda/faiss-gpu/meta.yaml
  thirdparty/faiss/contrib/evaluation.py
  thirdparty/faiss/faiss/Index.h
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexFlatCodes.h
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFAdditiveQuantizer.cpp
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/IndexRefine.h
  thirdparty/faiss/faiss/impl/AdditiveQuantizer.cpp
  thirdparty/faiss/faiss/impl/ProductQuantizer.cpp
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
  thirdparty/faiss/faiss/utils/hamming.cpp
  thirdparty/faiss/faiss/utils/hamming.h
  thirdparty/faiss/faiss/utils/partitioning.cpp
  thirdparty/faiss/tests/test_index_composite.py
  thirdparty/faiss/tests/test_refine.py
  thirdparty/faiss/tests/test_residual_quantizer.py
  thirdparty/faiss/tests/test_standalone_codec.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#238 Mmap support disk-load index
  include/knowhere/config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS
