Repository zilliztech/knowhere, pull requests merged in 2023-10, with the labels that each got.

#133 Fix ivf getvector concurrence bug
  src/index/ivf/ivf.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_ivfflat_cc.cc
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexBinaryIVF.h
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/invlists/DirectMap.cpp
  thirdparty/faiss/faiss/invlists/DirectMap.h
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/bug

#134 Move make offset map to load stage
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#115 fix a typo in IndexNode
  include/knowhere/index_node.h
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#136 Limit faiss ivf index build thread num
  include/knowhere/comp/thread_pool.h
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#122 Add a benchmark for Scann
  benchmark/hdf5/benchmark_float_qps.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#138 make ci analyzer (clang-tidy) faster
  .github/workflows/analyzer.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#137 opensource neon code
  .pre-commit-config.yaml
  cmake/libs/libfaiss.cmake
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/hook.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XL

#144 Make knowhere run on old cpus which only support sse4.2
  cmake/libs/libdiskann.cmake
  cmake/libs/libfaiss.cmake
  include/knowhere/config.h
  include/knowhere/expected.h
  src/common/index.cc
  src/index/hnsw/hnsw_config.h
  src/index/ivf/ivf_config.h
  src/simd/hook.cc
  src/simd/hook.h
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#150 Make Search() and RangeSearch() properly handle inner exceptions
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#151 Add a missing <future> header to test_get_vector.cc
  tests/ut/test_get_vector.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#145 pyknowhere - support dump and load index file
  .gitignore
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  tests/python/test_index_load_and_save.py
  tests/python/test_index_with_random.py
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/feature

#148 Record knowhere index build time
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#155 Fix a problem with faiss simdlib use v2
  cmake/libs/libfaiss.cmake
  thirdparty/faiss/faiss/impl/ResidualQuantizer.cpp
  thirdparty/faiss/faiss/impl/pq4_fast_scan.cpp
  thirdparty/faiss/faiss/utils/hamming-inl.h
  thirdparty/faiss/faiss/utils/jaccard-inl.h
  thirdparty/faiss/faiss/utils/partitioning.cpp
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#156 Add new ser/deser for scann index
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/IndexRefine.h
  thirdparty/faiss/faiss/IndexScaNN.cpp
  thirdparty/faiss/faiss/IndexScaNN.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#159 Add partitioning_avx2.cpp for PQFastScan
  cmake/libs/libfaiss.cmake
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
  thirdparty/faiss/faiss/utils/partitioning.h
  thirdparty/faiss/faiss/utils/partitioning_avx2.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#158 Add pyknowhere API to support binary GetVectorByIds
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#160 Add large topk tests
  tests/ut/test_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#163 Update supported simd in ut
  tests/ut/test_knowhere_init.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#164 Add gen_hdf_file.cpp to support create random dataset
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_hdf5.h
  benchmark/hdf5/gen_hdf5_file.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#165 Correct bitset support in pyknowhere
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#166 Add a missing header file
  benchmark/hdf5/gen_hdf5_file.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS
