Repository zilliztech/knowhere, pull requests merged in 2023-12, with the labels that each got.

#239 flush raft results ids
  src/common/raft/integration/raft_knowhere_index.cuh
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#217 Use knowhere-test refactor
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#247 fix: allow mergify apply to 2.x branch
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#251 Fix diskann cosine distance computation
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#250 Fix diskann async cache
  knowhere/index/vector_index/IndexDiskANN.cpp
  knowhere/index/vector_index/IndexDiskANN.h
  thirdparty/DiskANN/include/pq_flash_index.h
  thirdparty/DiskANN/include/semaphore.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: ci-passed, kind/improvement, approved, lgtm, size/XL

#249 chore(e2e-test): bump build image to amd64-ubuntu20.04-20231117-7a169d0
  ci/pod/e2e-cpu.yaml
Labels: kind/enhancement, dco-passed, do-not-merge/missing-related-issue, size/XS

#248 Use knowhere-test refactor
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#253 Remove search_list_and_k_ratio param
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#258 [2.2] Remove search_list_and_k_ratio param
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#260 [2.2] Add logs for DiskANN build
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#261 Log HNSW's build progress
  src/index/hnsw/hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#262 Fix concurrent log in DiskAnn build
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#265 Add logs for DiskAnn build
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#254 [Cherry-pick] mmap support diskload index (#238)
  include/knowhere/config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#266 [2.2] Fix cosine distance in DiskAnn BF
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#270 [2.2] Switch to brute force for hnsw when topk is super large (#219)
  tests/ut/test_iterator.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#236 Change default IVF_PQ build param m to 32
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#272 Update default IVF_PQ build param m to 32
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#282 fix(mergify): [skip e2e] lowercase K
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#283 Fix raft bug
  src/common/raft/integration/raft_knowhere_index.cuh
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#162 Initial ppc64le support
  cmake/libs/libfaiss.cmake
  cmake/utils/platform_check.cmake
  src/simd/hook.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#284 Switch to BF when K is too big (#271)
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#294 Remove useless prometheus metrics
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#295 pip3 install in requirement.txt order
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#299 Support search topk metric
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#298 Add prometheus metrics knowhere_load_latency
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#291 Do not allow n_lists to exceed number of rows for RAFT IVF
  src/common/raft/integration/raft_knowhere_index.cuh
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XS

#303 [cherry-pick]Pip3 install in requirements.txt order
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#300 Cherry-pick #294 #298 from main
  include/knowhere/prometheus_client.h
  src/common/index.cc
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#301 bypass some gpu test case
  tests/ut/test_gpu_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#304 Deprecate Invalid config checking
  src/common/config.cc
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#305 Deprecate Invalid config checking
  src/common/config.cc
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#306 Remove args that xargs can not recognized
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#307 Update Dockerfile to install python3.11
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#309 Update ci groovy file to use new docker image
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#310 Install pip3 for ci test run
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#292 Allow RAFT indexes to perform refinement after serialization
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/proto/raft_index.cuh
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#268 [Cherry Pick]Support Async cache making for DiskANN
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#314 prepare thread api for cardinal
  include/knowhere/comp/task.h
  src/common/thread/thread.cc
  tests/ut/test_range_util.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#315 Fix scann range search
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#317 Add pyknowhere API to set thread pool size for build and search
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#316 Fix scann range search
  thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#319 Optimize thread pool initialization
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#280 Move memory allocation out of elkan_L2_sse
  thirdparty/faiss/faiss/IndexFlatElkan.cpp
  thirdparty/faiss/faiss/IndexFlatElkan.h
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#318 Add more prometheus metrics
  cmake/libs/libdiskann.cmake
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/percentile_stats.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#313 add alias name for raft gpu index, milvus need.
  src/index/gpu_raft/gpu_raft_brute_force.cc
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
  tests/ut/test_knowhere_init.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm
