Repository zilliztech/knowhere, pull requests merged in 2024-03, with the labels that each got.

#434 fix compilation using clang-18
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#436 feat: add stale bot
  .github/workflows/stale.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#441 [skip ci] Update prepare_gpu_build.sh
  scripts/prepare_gpu_build.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#440 update impl of sparse inverted index to use unorder_map
  include/knowhere/sparse_utils.h
  src/index/sparse/sparse_inverted_index.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#430 Update e2e docker image to speed up knowhere build
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, approved, size/S, lgtm

#446 Fix deserialize materialized view null
  include/knowhere/comp/materialized_view.h
  src/common/comp/materialized_view.cc
  tests/ut/test_materialized_view_search_info.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/bug

#311 Add sq for hnsw
  include/knowhere/comp/index_param.h
  include/knowhere/utils.h
  src/index/hnsw/hnsw.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
  thirdparty/hnswlib/hnswlib/space_cosine.h
  thirdparty/hnswlib/hnswlib/space_ip.h
  thirdparty/hnswlib/hnswlib/space_l2.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XL, kind/feature

#451 Check simd type for scann index
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#460 Revert "Use conan to manage openblas"
  conanfile.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#458 Upload and download conan artifact to make ut build faster
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, approved, size/M, lgtm

#455 Add new param 'empty_result_nbucket' for IVF range search
  include/knowhere/comp/index_param.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  thirdparty/faiss/faiss/IndexBinaryIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#465 remove openblas from conanfile
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#468 Upgrade folly to run on arm
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#467 Add max_empty_result_buckerts for ScaNN range search
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexScaNN.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#464 Add new config type CFG_BYTES, and use it for trace_id and span_id
  include/knowhere/config.h
  include/knowhere/tracer.h
  src/common/comp/brute_force.cc
  src/common/index.cc
  src/common/tracer.cc
  tests/ut/test_config.cc
  tests/ut/test_tracer.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#470 Update run_id to make UT run faster
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#473 fix: specify cardinal clone path
  cmake/libs/libcardinal.cmake
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XS

#474 fix: remove some invalid uts
  tests/ut/test_diskann.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XS

#475 add a new cc index:ivf sq cc
  include/knowhere/comp/index_param.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexIVFScalarQuantizerCC.cpp
  thirdparty/faiss/faiss/IndexIVFScalarQuantizerCC.h
  thirdparty/faiss/faiss/utils/data_backup_file.cpp
  thirdparty/faiss/faiss/utils/data_backup_file.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#479 Update gpu knowhere docker image
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#481 Update max_empty_result_buckets default value to 2
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#480 fix UseDiskLoad interface
  python/knowhere/knowhere.i
  src/common/utils.cc
  tests/ut/test_utils.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/S, lgtm
