Repository zilliztech/knowhere, pull requests merged in 2024-11, with the labels that each got.

#924 raft index supports cosine similarity by normalizing the input data.
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/integration/raft_knowhere_index.hpp
  src/common/raft_metric.h
  src/index/gpu_raft/gpu_raft_brute_force_config.h
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#922 compensate for the missing acceleration functions in ARM NEON.
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#929 Allows FAISS_HNSW_FLAT index to load & search on hnswlib flat index
  include/knowhere/expected.h
  src/index/hnsw/base_hnsw_config.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/faiss_hnsw_config.h
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw.h
  src/index/hnsw/hnsw_config.h
  tests/ut/test_faiss_hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#930 enhance : use faiss hnsw implementation to replace hnswlib
  include/knowhere/comp/index_param.h
  include/knowhere/index/index_table.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw.h
  src/index/hnsw/impl/IndexBruteForceWrapper.cc
  src/index/index_static.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_index_check.cc
  tests/ut/test_iterator.cc
  tests/ut/test_search.cc
Labels: dco-passed, do-not-merge/missing-related-issue, approved, lgtm, size/L

#932 enable refine for FAISS HNSW indices by default, if available
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/faiss_hnsw_config.h
  src/index/hnsw/impl/IndexConditionalWrapper.cc
  src/index/hnsw/impl/IndexConditionalWrapper.h
  tests/ut/test_iterator.cc
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/IndexRefine.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#928 improve sparse vector index mmap: to mmap almost everything
  include/knowhere/sparse_utils.h
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/io/memory_io.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#934 fix: update faiss hnsw unit test for compatibility
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#935 sparse mmap mode to use a disk file as backed mmap mmeory
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#936 fix: add hnsw pq/prq refine check
  src/index/hnsw/faiss_hnsw_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#938 use MAP_PRIVATE for mmapped file
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#939 fix : fix code checker error in milvus pipeline
  src/io/file_io.h
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#940 enhance : optimize config check error msg
  include/knowhere/config.h
  src/common/config.cc
  src/index/diskann/diskann_config.h
  src/index/gpu_raft/gpu_raft_brute_force_config.h
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
  src/index/hnsw/base_hnsw_config.h
  src/index/hnsw/faiss_hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#941 enhance: BF supports ids of base_data starting from a specific value
  include/knowhere/bitsetview_idselector.h
  include/knowhere/comp/index_param.h
  include/knowhere/dataset.h
  src/common/comp/brute_force.cc
  tests/ut/test_bruteforce.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#944 sparse RangeSearch/AnnIterator to return raw distance
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#947 fix : update knowhere index version
  include/knowhere/version.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#946 enhance : update vector index defeault value
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#948 fix: BitsetViewSelectorHelper miss id_offset
  tests/ut/test_bruteforce.cc
  thirdparty/faiss/faiss/utils/distances.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#894 Add optimized distiance functions for PowerPC
  cmake/libs/libfaiss.cmake
  src/simd/distances_powerpc.cc
  src/simd/distances_powerpc.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#950 enhance: optimize get norms function with simd and reduce some calculations
  src/common/comp/brute_force.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#952 fix: Isolate faiss_hnsw and hnsw by index version
  src/index/hnsw/faiss_hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#954 [skip e2e] update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#955 enhance: pick prs from main for knowhere v2.3.13
  cmake/libs/libfaiss.cmake
  cmake/libs/libraft.cmake
  cmake/libs/librapids.cmake
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/expected.h
  include/knowhere/sparse_utils.h
  src/common/comp/brute_force.cc
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/integration/raft_knowhere_index.hpp
  src/common/raft/proto/raft_index.cuh
  src/common/raft_metric.h
  src/index/gpu_raft/gpu_raft_brute_force_config.h
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/faiss_hnsw_config.h
  src/index/ivf/ivf_config.h
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  src/io/memory_io.h
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_powerpc.cc
  src/simd/distances_powerpc.h
  src/simd/hook.cc
  tests/ut/test_config.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_check.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#957 Update benchmark for RAFT
  benchmark/benchmark_base.h
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/ref_logs/Makefile
  include/knowhere/comp/index_param.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#959 add support for android
  CMakeLists.txt
  cmake/libs/libfaiss.cmake
  cmake/utils/platform_check.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#960 delete useless deps for milvus lite on knowhere
  CMakeLists.txt
  conanfile.py
  src/common/comp/brute_force.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm
