Repository zilliztech/knowhere, pull requests merged in 2024-10, with the labels that each got.

#876 fix raft cpu search compile error
  src/index/gpu_raft/gpu_raft_cagra.cc
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS, do-not-merge/description-tag-conflict

#878 fix: Remove thread_priority in mac ThreadFactory constructor
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#874 Iterator for diskann
  include/knowhere/config.h
  src/index/diskann/diskann.cc
  tests/ut/test_diskann.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#881 Set resources limit for e2e-sse pod
  ci/pod/e2e-sse.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#883 [skip e2e] Update Cardinal Version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#873 async build support for cardinal
  include/knowhere/expected.h
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  include/knowhere/index/interrupt.h
  python/knowhere/knowhere.i
  src/index/index.cc
  src/index/interrupt.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#886 Do not check e2e-sse for ci
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#887 enhance: add a bit-based structure to mark index-specific features
  include/knowhere/feature.h
  include/knowhere/index/index.h
  include/knowhere/index/index_factory.h
  include/knowhere/operands.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_brute_force.cc
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.cc
  src/index/index_factory.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_index_check.cc
  tests/ut/test_index_node.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#889 fix async bug
  src/index/index.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XS

#895 fix: feature check ut
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#896 fix: update diskann config for config check
  include/knowhere/config.h
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#903 fix: update `dim` config & fix msg nullpointer error
  include/knowhere/config.h
  src/common/config.cc
  src/index/diskann/diskann_config.h
  src/index/gpu_raft/gpu_raft_brute_force_config.h
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
  src/index/hnsw/faiss_hnsw_config.h
  src/index/hnsw/hnsw_config.h
  src/index/index.cc
  src/index/ivf/ivf_config.h
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#906 fix: add FormatAndCheck for int64
  include/knowhere/config.h
  src/common/config.cc
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#910 [skip e2e] Update Cardinal Version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#914 update raft to 24.10
  cmake/libs/libraft.cmake
  cmake/libs/librapids.cmake
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/proto/raft_index.cuh
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#913 Fix group search
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/faiss_hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: kind/enhancement, dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, lgtm, size/L

#915 fix : add config check for open and closed range settings
  include/knowhere/config.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_config.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm
