Repository zilliztech/knowhere, pull requests merged in 2024-09, with the labels that each got.

#806 Update conan pack to save ut build time
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#808 Let HNSW throw exception when calculate distance for unsupported DataType
  thirdparty/hnswlib/hnswlib/space_cosine.h
  thirdparty/hnswlib/hnswlib/space_ip.h
  thirdparty/hnswlib/hnswlib/space_l2.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#810 Use cloud new_ci_idc
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#803 Set norm to 1.0 for all-0 vectors
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/index.cpp
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#811 Remove CFG_LIST and CFG_BYTES, and optimize error msg in config load
  include/knowhere/config.h
  scripts/run_codecov.sh
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#813 Update test_knowhere_init
  include/knowhere/comp/knowhere_config.h
  include/knowhere/comp/thread_pool.h
  src/common/comp/knowhere_config.cc
  tests/ut/test_knowhere_init.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#801 implement HasRawData() and GetVectorByIds() for faiss hnsw.
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_faiss_hnsw.cpp
  src/index/hnsw/faiss_hnsw.cc
  tests/ut/test_distances.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#817 Update test_index_check
  include/knowhere/comp/knowhere_check.h
  include/knowhere/index/index_table.h
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#814 Remove f16c flag in utils_sse
  cmake/libs/libfaiss.cmake
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#820 [skip e2e] Update Cardinal Version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#819 Fix typo in UT
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#824 fix knowhere ut
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#825 Set 4c16g for e2e-cpu and 8c30g for e2e-gpu
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#826 Update e2e groovy
  ci/E2E-arm.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#818 Update test_utils with ThreadPool test
  include/knowhere/comp/thread_pool.h
  tests/ut/test_utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#835 Temporary solution to fix omp threads spawned
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#831 Add test_index_node
  tests/ut/test_index_node.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#838 Update e2e timeout to 60 minutes
  ci/E2E-arm.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#828 Apple clang
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#839 use libopenblas-openmp-dev
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  README.md
  ci/E2E-arm.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
  scripts/install_deps.sh
  scripts/python_deps.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#827 modify the API to use smart pointers to pave the way for the async
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  include/knowhere/index/index_node_thread_pool_wrapper.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.cc
  src/index/index.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/index_node_thread_pool_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_node.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#843 [skip ci] Update docker builder groovy
  ci/BuildCPUBuilderImage.groovy
  ci/BuildGPUBuilderImage.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#845 [skip ci] Update docker builder groovy
  ci/BuildCPUBuilderImage.groovy
  ci/BuildGPUBuilderImage.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#846 [skip ci] Update docker builder groovy
  ci/BuildCPUBuilderImage.groovy
  ci/BuildGPUBuilderImage.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#849 Update ci docker image
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#844 enable e2e on sse machine
  .github/mergify.yml
  ci/E2E2-SSE.groovy
  ci/pod/e2e-sse.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#850 Add more unittest for src/common
  include/knowhere/comp/thread_pool.h
  src/common/config.cc
  src/common/tracer.cc
  src/common/utils.cc
  tests/ut/test_config.cc
  tests/ut/test_tracer.cc
  tests/ut/test_utils.cc
Labels: dco-passed, kind/improvement, approved, lgtm, size/L

#852 Add e2e(arm) in mergify
  .github/mergify.yml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#836 add knowhere static interface
  include/knowhere/comp/knowhere_check.h
  include/knowhere/config.h
  include/knowhere/expected.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_static.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/faiss_hnsw_config.h
  src/index/hnsw/hnsw.cc
  src/index/index_static.cc
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_diskann.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_check.cc
  tests/ut/test_index_node.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  tests/ut/test_sparse.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XL

#841 fix: fail to load ivf_flat(metric = cosine) with DeserializeFromFile
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.cpp
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#857 [skip e2e] Update Cardinal Version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#858 Skip coverage check for trace code
  src/common/comp/brute_force.cc
  src/index/index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#863 Set scoped omp to fix IVF index build degrade
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/ref_logs/Makefile
  include/knowhere/comp/thread_pool.h
  src/common/comp/brute_force.cc
  src/common/thread/thread.cc
  src/index/flat/flat.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#866 fix memory usage
  include/knowhere/config.h
  src/index/index_static.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#867 Update test_simd
  src/simd/hook.cc
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#853 FAISS HNSW range search
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/impl/IndexBruteForceWrapper.cc
  src/index/hnsw/impl/IndexBruteForceWrapper.h
  src/index/hnsw/impl/IndexConditionalWrapper.cc
  src/index/hnsw/impl/IndexConditionalWrapper.h
  src/index/hnsw/impl/IndexHNSWWrapper.cc
  src/index/hnsw/impl/IndexHNSWWrapper.h
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_iterator.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexBruteForceWrapper.cpp
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexBruteForceWrapper.h
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexHNSWWrapper.cpp
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexHNSWWrapper.h
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexWrapper.cpp
  thirdparty/faiss/faiss/cppcontrib/knowhere/IndexWrapper.h
  thirdparty/faiss/faiss/cppcontrib/knowhere/impl/Bruteforce.h
  thirdparty/faiss/faiss/cppcontrib/knowhere/impl/HnswSearcher.h
Labels: kind/enhancement, dco-passed, approved, lgtm, size/XXL

#868 enhance: Update default thread priority
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, kind/improvement, approved, size/M, lgtm

#872 Remove Cache for graph search
  src/common/config.cc
  src/common/lru_cache.h
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/faiss/faiss/cppcontrib/knowhere/impl/HnswSearcher.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#875 faiss hnsw: get rid of a debugging config option
  src/index/hnsw/faiss_hnsw_config.h
  src/index/hnsw/impl/IndexConditionalWrapper.cc
Labels: dco-passed, kind/improvement, approved, size/S, lgtm
