Repository zilliztech/knowhere, pull requests merged in 2024-01, with the labels that each got.

#323 Add some params check for cagra
  src/index/gpu_raft/gpu_raft_cagra_config.h
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#322 Shuffle ids for building graph index
  include/knowhere/config.h
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
  thirdparty/DiskANN/include/diskann/aux_utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#321 fix GPU_IVF_PQ double define
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#325 Add labels for all prometheus metrics
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#324 Add SetThreadPoolSize interface
  include/knowhere/comp/thread_pool.h
  src/common/comp/knowhere_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#331 chore(deps): bump conan version to 1.61.0
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#210 Knowhere support multi data type
  .github/workflows/release-python.yml
  .github/workflows/ut.yaml
  README.md
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/comp/brute_force.h
  include/knowhere/dataset.h
  include/knowhere/factory.h
  include/knowhere/index.h
  include/knowhere/index_node.h
  include/knowhere/index_node_data_mock_wrapper.h
  include/knowhere/operands.h
  include/knowhere/utils.h
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  src/common/comp/brute_force.cc
  src/common/factory.cc
  src/common/index_node_data_mock_wrapper.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_brute_force.cc
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/python/conftest.py
  tests/python/test_index_load_and_save.py
  tests/python/test_index_random.py
  tests/ut/test_bruteforce.cc
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_half_presicion.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
  thirdparty/DiskANN/include/diskann/utils.h
Labels: dco-passed, ci-passed, approved, lgtm, kind/feature, size/XXL

#330 Make storage of dataset on device for refinement optional
  CMakeLists.txt
  include/knowhere/comp/index_param.h
  src/common/raft/integration/raft_knowhere_config.hpp
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/proto/raft_index.cuh
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  src/index/gpu_raft/gpu_raft_ivf_pq_config.h
  tests/ut/test_gpu_search.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#342 avoid low version gcc explicit instantiation failed
  benchmark/hdf5/gen_fbin_file.cpp
  benchmark/hdf5/gen_hdf5_file.cpp
  src/common/comp/brute_force.cc
  src/common/factory.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#344 use new double_pop_list to replace neighborset;
  include/knowhere/bitsetview.h
  src/common/index.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/neighbor.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#346 Add IsAdditionalScalarSupported interface for compatibility
  include/knowhere/index.h
  include/knowhere/index_node.h
  src/common/index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#349 Support OpenTelemetry tracer
  CMakeLists.txt
  conanfile.py
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/tracer.h
  src/common/comp/knowhere_config.cc
  src/common/index.cc
  src/common/tracer.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#350 Update gpu Dockerfile cuda version to 11.8.0
  CMakeLists.txt
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XS

#340 Add edges for those unreachable nodes to improve graph connectivity
  src/index/hnsw/hnsw.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#351 Use conan to manage openblas
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#347 Upgrade conan to 1.61.0 (#182)
  .github/workflows/analyzer.yaml
  .github/workflows/ut.yaml
  README.md
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  scripts/install_deps.sh
  scripts/python_deps.sh
Labels: dco-passed, kind/improvement, approved, size/S, lgtm

#353 Ensure topk results for IVF_FLAT_CC
  include/knowhere/comp/index_param.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
  thirdparty/faiss/faiss/IndexIVFSpectralHash.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.cpp
  thirdparty/faiss/faiss/impl/ScalarQuantizerScanner.h
  thirdparty/faiss/tests/test_lowlevel_ivf.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#357 fix:miss wait thread tasks finish in diskann.
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#358 Add more comments and uts for #353
  src/index/ivf/ivf_config.h
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexIVF.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#355 make sure we rethrow exceptions in async tasks
  include/knowhere/comp/thread_pool.h
  src/common/comp/brute_force.cc
  src/common/thread/thread.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_utils.cc
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#341 [feat] Add sparse index support to knowhere
  include/knowhere/comp/brute_force.h
  include/knowhere/comp/index_param.h
  include/knowhere/dataset.h
  include/knowhere/operands.h
  include/knowhere/sparse_utils.h
  src/common/comp/brute_force.cc
  src/common/factory.cc
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_sparse.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, approved, lgtm, kind/feature, size/XXL

#359 wrap IVF index train/build calls in knowhere build pool
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
