Repository zilliztech/knowhere, pull requests merged in 2024-05, with the labels that each got.

#542 Fix LAPACK not found
  cmake/libs/libfaiss.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#514 add a no gpu memory pool resource
  src/common/raft/integration/raft_knowhere_index.cuh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#549 Add binary support for pyknowhere
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#550 Binary vector from/to np.uint8 array in pyknowhere api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#538 fix compiler warnings
  tests/ut/test_utils.cc
  thirdparty/DiskANN/include/diskann/linux_aligned_file_reader.h
  thirdparty/faiss/faiss/utils/binary_distances.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#553 Update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#554 [Bugfix] Add patch for bf16 distance computation
  include/knowhere/comp/knowhere_config.h
  include/knowhere/operands.h
  src/common/comp/knowhere_config.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_type.cc
  tests/ut/utils.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#558 [skip ci] Update docker builder default os to ubuntu22.04
  ci/BuildCPUBuilderImage.groovy
  ci/BuildGPUBuilderImage.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#559 only search use GPU memory pool
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/integration/raft_knowhere_index.hpp
  src/index/gpu_raft/gpu_raft.h
Labels: bug, kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#566 [skip e2e] Release cardinal for milvus 2.4
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#564 Fix a typo
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
  thirdparty/faiss/faiss/gpu/impl/IcmEncoder.cuh
  thirdparty/faiss/tests/test_local_search_quantizer.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#562 Cherry-pick commit #3416 from Faiss baseline
  thirdparty/faiss/faiss/impl/platform_macros.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#574 Fix kmeans init dead loop when dist is inf
  thirdparty/DiskANN/src/math_utils.cpp
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#576 [skip ci] Update Dockerfile to use gcc-12/g++-12 for ubuntu22.04
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#578 [skip ci] Update gpu Dockerfile for ubuntu22.04
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#580 [feat] ci pipeline on cloud arm machine
  ci/E2E-arm.groovy
  ci/pod/e2e-arm-cpu.yaml
Labels: dco-passed, do-not-merge/missing-related-issue, size/L

#581 fix: change image
  ci/pod/e2e-arm-cpu.yaml
Labels: size/XS

#561 Update docker image to ubuntu22.04 for ci
  .github/workflows/ut.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#583 chore(ci): support arm build env
  ci/BuildArmCPUBuilderImage.groovy
  ci/pod/rte-arm.yaml
Labels: size/L

#584 [skip e2e] Update cardinal commit
  cmake/libs/libcardinal.cmake
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS, do-not-merge/description-tag-conflict

#567 Upgrade index version
  include/knowhere/version.h
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS, do-not-merge/description-tag-conflict

#588 [skip ci] Add arm64 Dockerfile
  ci/BuildArmCPUBuilderImage.groovy
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#589 [skip ci] Optimize arm64 Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#587 [skip e2e] Update cardinal tag
  .github/workflows/ut.yaml
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#590 [skip ci] Optimize arm64 Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#591 [skip ci] Optimize arm64 Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#592 [skip ci] Optimize arm64 Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#594 [skip ci] Optimize cpu/gpu Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#586 feat: add Size interface for binaryset
  README.md
  include/knowhere/binaryset.h
  tests/ut/test_binaryset.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#596 Update ci docker image to ubuntu22.04 and gcc-12
  .github/workflows/ut.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#603 [skip ci] Pre-install bfloat16 whl in docker image
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#604 [skip ci] Fix a typo error in arm64 Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#606 chore(ci): allow more pr run at once
  ci/pod/e2e-cpu.yaml
Labels: size/S

#608 [skip ci] Require more resource for e2e run
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#599 remove seed_ef and use ef for hnsw iterator
  include/knowhere/comp/index_param.h
  src/common/config.cc
  src/index/hnsw/hnsw.cc
  src/index/hnsw/hnsw_config.h
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_iterator.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#605 Use docker image with bfloat16 pre-installed
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#601 Fix iterator based range search
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#615 [skip ci] Update Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#617 Update docker image
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#621 chore(ci):fix
  ci/pod/e2e-arm-cpu.yaml
Labels: size/XS
