Repository zilliztech/knowhere, pull requests merged in 2024-08, with the labels that each got.

#715 Encode & Decode traceID and spanID as hex string
  include/knowhere/config.h
  include/knowhere/tracer.h
  src/common/comp/brute_force.cc
  src/common/tracer.cc
  src/index/index.cc
  tests/ut/test_config.cc
  tests/ut/test_tracer.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L

#744 improve SQ6 code for AVX512
  cmake/libs/libfaiss.cmake
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#749 [skip ci] Handle angular dataset as COSINE for benchmark
  benchmark/hdf5/benchmark_hdf5.h
Labels: dco-passed, do-not-merge/missing-related-issue, approved, lgtm, size/XS

#754 Add a special OpenBLAS header handling for PowerPC
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#755 iterator with order
  include/knowhere/config.h
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#751 [Enhancement] add statically hasRawData interface
  include/knowhere/comp/knowhere_check.h
  src/index/flat/flat.cc
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#760 expose knowhere config as C api
  include/knowhere/config.h
  src/common/config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#764 enhance: increase range search default param
  src/index/hnsw/hnsw_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#766 range_search (based on iterator) support retain_iterator_order
  include/knowhere/comp/index_param.h
  include/knowhere/index/index_node.h
  tests/ut/test_iterator.cc
  tests/ut/test_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#772 ivf_sq support iterator
  src/index/ivf/ivf.cc
  tests/ut/test_iterator.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerScanner.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#783 Remove redundant e2e steps
  ci/E2E-arm.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, lgtm, size/XS

#775 fix InvertedIndex::Train when all input vectors are empty
  include/knowhere/config.h
  src/index/sparse/sparse_inverted_index.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#781 [iterator_range_search] remove min_exceed_cnt
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#773 Show illegal vector value in diskann
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#786 Copy test data to local to save runtime
  ci/E2E-arm.groovy
  ci/E2E2.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#788 Revert "Copy test data to local to save runtime (#786)"
  ci/E2E-arm.groovy
  ci/E2E2.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#791 fix uncompilable test_sparse UT
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS, kind/bug, do-not-merge/description-tag-conflict

#792 [skip ci] Update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#797 Use simd norm for all data type
  src/common/utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#798 Rename Normalize to NormalizeDataset
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/ivf/ivf.cc
  tests/ut/test_utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#800 Add API description for index_node
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
