Repository zilliztech/knowhere, pull requests merged in 2024-02, with the labels that each got.

#370 Add trace span in bruteforce search
  src/common/comp/brute_force.cc
  src/common/tracer.cc
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/feature

#374 gpu rawdata return false, reduce cpu usage with gpu index
  src/index/gpu_raft/gpu_raft.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#376 Add more attr for trace span
  include/knowhere/comp/index_param.h
  include/knowhere/tracer.h
  src/common/comp/brute_force.cc
  src/common/index.cc
  src/common/tracer.cc
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/feature

#369 Add iterator support to brute force search
  include/knowhere/comp/brute_force.h
  include/knowhere/config.h
  src/common/comp/brute_force.cc
  tests/ut/test_iterator.cc
  thirdparty/faiss/faiss/impl/ResultHandler.h
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#378 fix: use WaitAllSuccess replace future.wait() in diskann function
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#384 switch knowhere-test branch to 2.2
  ci/E2E2.groovy
Labels: dco-passed, do-not-merge/missing-related-issue, approved, size/XS

#383 [2.2] Ensure topk results for IVF_FLAT_CC (#353)
  include/knowhere/comp/index_param.h
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFPQ.cpp
  thirdparty/faiss/faiss/IndexIVFSpectralHash.cpp
  thirdparty/faiss/faiss/IndexIVFThreadSafe.cpp
  thirdparty/faiss/faiss/IndexScalarQuantizer.cpp
  thirdparty/faiss/faiss/impl/ScalarQuantizer.h
  thirdparty/faiss/tests/test_lowlevel_ivf.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#382 [fix 2.2]: make sure we rethrow exceptions in async tasks
  include/knowhere/comp/thread_pool.h
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_utils.cc
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#379 [2.2 fix] wrap IVF index train/build calls in knowhere build pool
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#377 [2.2] fix diskann async cache generation
  CMakeLists.txt
  cmake/utils/compile_flags.cmake
  include/knowhere/comp/thread_pool.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#380 fix:miss wait thread tasks finish in diskann.
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#381 [2.2] Shuffle ids for building hnsw index (#322)
  include/knowhere/config.h
  src/index/diskann/diskann.cc
  src/index/hnsw/hnsw.cc
  thirdparty/DiskANN/include/diskann/aux_utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
Labels: dco-passed, kind/improvement, approved, size/M

#386 pick: clear futures when all task finished
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, approved, lgtm, size/XS, kind/bug

#389 fix: ivf-iterator will own the bw_idselector
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#392 fix: [cp] DiskANN Build Percentage
  thirdparty/DiskANN/src/partition_and_pq.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#395 Update ci docker image and optimize gpu build
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/ut-gpu.yaml
  scripts/prepare_gpu_build.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#396 Replace gettid() with syscall(SYS_gettid)
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#400 Add linking stdc++fs to tests/ut cmake list
  tests/ut/CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#406 fix: diskann memory leak after failure
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/cached_io.h
  thirdparty/DiskANN/include/diskann/logger_impl.h
  thirdparty/DiskANN/include/diskann/math_utils.h
  thirdparty/DiskANN/include/diskann/partition_and_pq.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/pq_table.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/logger.cpp
  thirdparty/DiskANN/src/math_utils.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/DiskANN/src/utils.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/bug

#373 fix diskann async cache generation
  CMakeLists.txt
  cmake/utils/compile_flags.cmake
  include/knowhere/comp/thread_pool.h
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#411 remove special CMAKE_CUDA_ARCHITECTURES, aligned with raft.
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#408 double ci timeout
  ci/E2E2.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#417 Optimize ut CMakeLists.txt
  tests/ut/CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#418 Add convenient data_byte_size method to SparseRow
  include/knowhere/sparse_utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#420 Add DeserializeFromFile for pyknowhere
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#413 optimize README
  README.md
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#415 enhance: add materialized view search info for compatibility
  include/knowhere/comp/index_param.h
  include/knowhere/comp/materialized_view.h
  include/knowhere/config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#393 diskann support new data type(fp16/bf16)
  include/knowhere/operands.h
  src/index/diskann/diskann.cc
  thirdparty/DiskANN/include/diskann/distance.h
  thirdparty/DiskANN/include/diskann/index.h
  thirdparty/DiskANN/include/diskann/pq_flash_index.h
  thirdparty/DiskANN/include/diskann/utils.h
  thirdparty/DiskANN/src/aux_utils.cpp
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/partition_and_pq.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#409 The thread pool size is related to the number of gpu.
  CMakeLists.txt
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_brute_force.cc
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#422 reduce ut run time
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_half_presicion.cc
  tests/ut/test_mmap.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#426 Move test_mmap to knowhere_test
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  tests/ut/test_mmap.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#424 Update Readme
  README.md
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#427 Split UT stage for build and run
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#428 [skip ci] Update Dockerfile to install knowhere dependancies
  ci/docker/builder/cpu/ubuntu20.04/Dockerfile
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#431 [skip ci] Fix gpu Dockerfile error
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS
