Repository zilliztech/knowhere, pull requests merged in 2024-04, with the labels that each got.

#484 Softly check whether the gpu is avalid and whether the index is availab…
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/expected.h
  include/knowhere/factory.h
  python/knowhere/knowhere.i
  src/common/comp/knowhere_config.cc
  src/common/factory.cc
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#483 Add iterator support to sparse inverted index
  include/knowhere/index_node.h
  include/knowhere/sparse_utils.h
  src/common/comp/brute_force.cc
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_iterator.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L, kind/feature

#490 enhance: Get task count in the thread pool
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#492 fix crash on arm64
  conanfile.py
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#496 [skip e2e] chore(deps): bump codecov-action version
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#495 remove two unused variables
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#499 [improvement] Make MAP_POPULATE configurable
  include/knowhere/config.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/S, lgtm

#504 Fix create index log
  src/common/factory.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#502 knowhere light for milvus local
  CMakeLists.txt
  cmake/libs/libcardinal.cmake
  cmake/libs/libdiskann.cmake
  cmake/libs/libfaiss.cmake
  cmake/libs/libraft.cmake
  cmake/libs/librapids.cmake
  cmake/utils/compile_flags.cmake
  cmake/utils/platform_check.cmake
  src/common/comp/brute_force.cc
  src/common/index.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/L

#506 Fix SQ4 AVX-512 implementation
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#505 make IdVal more generic
  include/knowhere/index_node.h
  include/knowhere/object.h
  include/knowhere/sparse_utils.h
  src/common/comp/brute_force.cc
  src/index/sparse/sparse_inverted_index.h
  thirdparty/faiss/faiss/impl/ResultHandler.h
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#501 Add a common subclass for IndexNode::iterator
  include/knowhere/config.h
  include/knowhere/index_node.h
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_iterator.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFlat.cpp
  thirdparty/faiss/faiss/IndexIVFFlat.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
  thirdparty/hnswlib/hnswlib/hnswlib.h
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XL

#509 make DataSet gen helpers available to pyknowhere
  include/knowhere/dataset.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#448 Support cluster framework
  CMakeLists.txt
  benchmark/hdf5/benchmark_knowhere.h
  cmake/libs/libfaiss.cmake
  include/knowhere/cluster/cluster.h
  include/knowhere/cluster/cluster_factory.h
  include/knowhere/cluster/cluster_node.h
  include/knowhere/comp/brute_force.h
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/expected.h
  include/knowhere/index/index.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  include/knowhere/index/index_node_thread_pool_wrapper.h
  include/knowhere/utils.h
  python/knowhere/knowhere.i
  src/cluster/cluster.cc
  src/cluster/cluster_factory.cc
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_brute_force.cc
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_ivf_flat.cc
  src/index/gpu_raft/gpu_raft_ivf_pq.cc
  src/index/hnsw/hnsw.cc
  src/index/index.cc
  src/index/index_factory.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/index_node_thread_pool_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/CMakeLists.txt
  tests/ut/test_cluster.cc
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_range_util.cc
  tests/ut/test_search.cc
  tests/ut/test_sparse.cc
  tests/ut/utils.h
  thirdparty/DiskANN/include/diskann/utils.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XL, kind/feature

#516 remove no-as-needed
  cmake/utils/compile_flags.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#510 merging more changes from the faiss baseline
  thirdparty/faiss/.circleci/config.yml
  thirdparty/faiss/benchs/bench_cppcontrib_sa_decode.cpp
  thirdparty/faiss/benchs/link_and_code/README.md
  thirdparty/faiss/benchs/link_and_code/bench_link_and_code.py
  thirdparty/faiss/benchs/link_and_code/datasets.py
  thirdparty/faiss/benchs/link_and_code/neighbor_codec.py
  thirdparty/faiss/c_api/clone_index_c.cpp
  thirdparty/faiss/c_api/clone_index_c.h
  thirdparty/faiss/c_api/index_factory_c.cpp
  thirdparty/faiss/c_api/index_factory_c.h
  thirdparty/faiss/conda/faiss-gpu-raft/meta.yaml
  thirdparty/faiss/contrib/ondisk.py
  thirdparty/faiss/contrib/torch_utils.py
  thirdparty/faiss/demos/demo_imi_pq.cpp
  thirdparty/faiss/demos/offline_ivf/config_ssnpp.yaml
  thirdparty/faiss/demos/offline_ivf/offline_ivf.py
  thirdparty/faiss/demos/rocksdb_ivf/RocksDBInvertedLists.cpp
  thirdparty/faiss/demos/rocksdb_ivf/RocksDBInvertedLists.h
  thirdparty/faiss/faiss/CMakeLists.txt
  thirdparty/faiss/faiss/IndexHNSW.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
  thirdparty/faiss/faiss/impl/FaissAssert.h
  thirdparty/faiss/faiss/impl/HNSW.cpp
  thirdparty/faiss/faiss/impl/HNSW.h
  thirdparty/faiss/faiss/impl/LocalSearchQuantizer.cpp
  thirdparty/faiss/faiss/impl/ResultHandler.h
  thirdparty/faiss/faiss/impl/io.cpp
  thirdparty/faiss/faiss/impl/io.h
  thirdparty/faiss/faiss/invlists/BlockInvertedLists.cpp
  thirdparty/faiss/faiss/invlists/BlockInvertedLists.h
  thirdparty/faiss/faiss/invlists/DirectMap.cpp
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.cpp
  thirdparty/faiss/faiss/invlists/OnDiskInvertedLists.h
  thirdparty/faiss/faiss/python/swigfaiss.swig
  thirdparty/faiss/faiss/utils/simdlib.h
  thirdparty/faiss/faiss/utils/simdlib_avx512.h
  thirdparty/faiss/faiss/utils/simdlib_neon.h
  thirdparty/faiss/tests/CMakeLists.txt
  thirdparty/faiss/tests/test_contrib.py
  thirdparty/faiss/tests/test_fast_scan_ivf.py
  thirdparty/faiss/tests/test_graph_based.py
  thirdparty/faiss/tests/test_index_binary.py
  thirdparty/faiss/tests/test_merge.cpp
  thirdparty/faiss/tests/test_merge_index.py
  thirdparty/faiss/tests/test_search_params.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#518 Use specific commit rather than branch
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#517 removed unused range util for faiss
  include/knowhere/range_util.h
  src/common/range_util.cc
  src/index/flat/flat.cc
  tests/ut/test_range_util.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#520 [skip e2e] Force to checkout everytime unless env var set
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#522 remove accidentally added duplicate file
  include/knowhere/index/index_node.h
  include/knowhere/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#525 [fix] Add patch for bf16 distance computation
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
Labels: kind/enhancement, dco-passed, approved, size/S, lgtm

#526 [cherry-pick] AIX-related patches from the Faiss baseline
  thirdparty/faiss/contrib/vecs_io.py
  thirdparty/faiss/faiss/cppcontrib/detail/UintReader.h
  thirdparty/faiss/faiss/cppcontrib/sa_decode/Level2-inl.h
  thirdparty/faiss/faiss/impl/platform_macros.h
  thirdparty/faiss/faiss/impl/pq4_fast_scan.cpp
  thirdparty/faiss/faiss/python/CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#524 [cherrypick] Unroll loop in lookup_2_lanes for PQFasfScan for PPC64
  thirdparty/faiss/faiss/utils/simdlib.h
  thirdparty/faiss/faiss/utils/simdlib_ppc64.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#527 fix compiler warnings
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
  thirdparty/faiss/faiss/utils/simdlib_avx2.h
  thirdparty/hnswlib/hnswlib/space_cosine.h
  thirdparty/hnswlib/hnswlib/space_ip.h
  thirdparty/hnswlib/hnswlib/space_l2.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#532 Bitset valid check
  src/index/index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#533 Update cardinal link rule for better development convenience
  CMakeLists.txt
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
