Repository zilliztech/knowhere, pull requests merged in 2024-12, with the labels that each got.

#965 optimize conanfile
  conanfile.py
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm, do-not-merge/description-tag-conflict

#972 fix: conan: make glog shared
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#975 enhance: pick prs from main for knowhere v2.3.14
  cmake/libs/libcardinal.cmake
  cmake/utils/compile_flags.cmake
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#976 Update docker image for ci
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/e2e-sse.yaml
  ci/pod/ut-gpu.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#979 Fix build error
  cmake/libs/libfaiss.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#983 [skip ci] Update Dockerfile to support gcc-12 better
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#985 [skip ci] Update Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/Dockerfile
  ci/docker/builder/cpu/ubuntu22.04/arm64/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#984 Update docker image to fix arm build error
  ci/pod/e2e-arm-cpu.yaml
  ci/pod/e2e-cpu.yaml
  ci/pod/e2e-gpu.yaml
  ci/pod/e2e-sse.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#980 enhance: BF functions support real fp16/bf16 calculate
  include/knowhere/operands.h
  src/common/comp/brute_force.cc
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_bruteforce.cc
  tests/ut/test_simd.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/utils/distances_if.h
  thirdparty/faiss/faiss/utils/half_precision_floating_point_distances.cpp
  thirdparty/faiss/faiss/utils/half_precision_floating_point_distances.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#990 Optimize feature registry
  include/knowhere/index/index_factory.h
  src/index/index_factory.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#993 Fix some build warnings
  benchmark/hdf5/benchmark_float_qps.cpp
  src/common/comp/brute_force.cc
  tests/ut/test_bruteforce.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/faiss/faiss/cppcontrib/knowhere/impl/Neighbor.h
  thirdparty/faiss/faiss/impl/ResultHandler.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#994 Update conan pack to save UT build time
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#991 faiss_hnsw support INT8
  include/knowhere/comp/index_param.h
  include/knowhere/feature.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  include/knowhere/operands.h
  include/knowhere/utils.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/index_factory.cc
  src/index/index_static.cc
  tests/ut/test_config.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#996 Enable mmap-ped Faiss indices (IndexFlatCodes-based and HNSW)
  src/index/flat/flat.cc
  src/index/hnsw/faiss_hnsw.cc
  thirdparty/faiss/faiss/IndexFlatCodes.cpp
  thirdparty/faiss/faiss/IndexFlatCodes.h
  thirdparty/faiss/faiss/impl/HNSW.cpp
  thirdparty/faiss/faiss/impl/HNSW.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/mapped_io.cpp
  thirdparty/faiss/faiss/impl/mapped_io.h
  thirdparty/faiss/faiss/impl/maybe_owned_vector.h
  thirdparty/faiss/faiss/index_io.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#999 fix : adapt for cardinal ci
  include/knowhere/index/index_factory.h
  tests/ut/test_config.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_index_check.cc
Labels: kind/enhancement, dco-passed, do-not-merge/missing-related-issue, approved, lgtm, size/L

#1000 Optimize benchmark to show data type info
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/ref_logs/Makefile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1002 [skip e2e] Optimize qps benchmark to show real recall
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/ref_logs/Makefile
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#992 enhance: scann support iterator
  src/index/ivf/ivf.cc
  tests/ut/test_iterator.cc
  thirdparty/faiss/faiss/IndexIVF.cpp
  thirdparty/faiss/faiss/IndexIVF.h
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexIVFFastScan.h
  thirdparty/faiss/faiss/IndexScaNN.cpp
  thirdparty/faiss/faiss/IndexScaNN.h
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1005 make FileReader to close fd using RAII
  src/io/file_io.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1010 Optimize benchmark for SCANN & HNSW
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/ref_logs/Makefile
  include/knowhere/comp/index_param.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
