Repository zilliztech/knowhere, pull requests merged in 2024-06, with the labels that each got.

#627 fix: make GetIsSparse const
  include/knowhere/dataset.h
Labels: ci-passed, kind/improvement, approved, lgtm, size/XS, needs-dco

#634 check the combination of index type and data type
  include/knowhere/comp/index_param.h
  include/knowhere/comp/knowhere_check.h
  include/knowhere/index/index_factory.h
  src/index/hnsw/hnsw.cc
  src/index/index_factory.cc
  tests/ut/test_index_check.cc
Labels: do-not-merge/missing-related-issue, approved, lgtm, size/L, needs-dco

#635 add sparse support type in knowherecheck
  include/knowhere/comp/knowhere_check.h
Labels: do-not-merge/missing-related-issue, approved, lgtm, size/XS, needs-dco

#637 [skip ci] Add diskann benchmark test
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  benchmark/hdf5/ref_logs/Makefile
Labels: dco-passed, kind/improvement, approved, lgtm, size/L

#638 register index(binary_hnsw) in knowhere
  src/index/hnsw/hnsw.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#636 [skip e2e] : remove iterator/sparse ut limit for cardinal
  cmake/libs/libcardinal.cmake
  tests/ut/CMakeLists.txt
Labels: dco-passed, kind/improvement, approved, lgtm, size/XS

#625 Params for iterator
  include/knowhere/config.h
  src/index/diskann/diskann_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#640 [skip ci] Fix diskann benchmark fail
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
Labels: dco-passed, kind/improvement, approved, size/S, lgtm

#646 [skip ci] Update range search benchmark result display
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
Labels: dco-passed, kind/improvement, approved, size/S, lgtm

#648 [skip ci] Update script prepare_gpu_build.sh for nightly build
  scripts/prepare_gpu_build.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#649 Update index and data type check function
  include/knowhere/comp/index_param.h
  include/knowhere/comp/knowhere_check.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  include/knowhere/utils.h
  src/index/index_factory.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, do-not-merge/missing-related-issue, approved, size/L

#653 Add data type conversion test
  tests/ut/test_type.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#656 Update BruteForce ut for multi data type
  tests/ut/test_bruteforce.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#657 Clean build warnings
  benchmark/hdf5/benchmark_hdf5.h
  benchmark/hdf5/gen_hdf5_file.cpp
  src/index/index.cc
  tests/ut/test_range_util.cc
  thirdparty/DiskANN/src/index.cpp
  thirdparty/DiskANN/src/pq_flash_index.cpp
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexIVFPQFastScan.cpp
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
  thirdparty/faiss/faiss/utils/distances_if.h
  thirdparty/faiss/faiss/utils/distances_simd.cpp
  thirdparty/faiss/faiss/utils/hamming_distance/generic-inl.h
  thirdparty/faiss/faiss/utils/partitioning_avx2.cpp
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#654 Support numpy array to sparse dataset in pyknowhere api
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#661 cagra support train on gpu, search on cpu, use hnswlib
  include/knowhere/comp/index_param.h
  src/common/raft/integration/raft_knowhere_index.cuh
  src/common/raft/integration/raft_knowhere_index.hpp
  src/common/raft/proto/raft_index.cuh
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/gpu_raft/gpu_raft_cagra_config.h
  src/index/gpu_raft/gpu_raft_ivf_flat_config.h
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L, kind/feature, do-not-merge/description-tag-conflict

#659 Add following APIs to facilitate DataSet conversion
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/index/index_node_data_mock_wrapper.cc
  tests/ut/test_bruteforce.cc
  tests/ut/test_diskann.cc
  tests/ut/test_type.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#667 Update all APIs' input parameter to 'const DataSetPtr'
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
  include/knowhere/comp/brute_force.h
  include/knowhere/dataset.h
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  include/knowhere/index/index_node_thread_pool_wrapper.h
  include/knowhere/utils.h
  python/knowhere/knowhere.i
  src/common/comp/brute_force.cc
  src/common/utils.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_raft/gpu_raft.h
  src/index/gpu_raft/gpu_raft_cagra.cc
  src/index/hnsw/hnsw.cc
  src/index/index.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/index_node_thread_pool_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
  tests/ut/test_simd.cc
  tests/ut/test_sparse.cc
  tests/ut/test_utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#664 not check diskann range_search params max_k < min_k if with_cardinal
  tests/ut/test_diskann.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#665 fix aix compilation
  cmake/libs/libfaiss.cmake
  tests/ut/test_type.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#671 [range search] iterator stops only if exceeds radius several times consecutively.
  include/knowhere/config.h
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm
