Repository zilliztech/knowhere, pull requests merged in 2024-07, with the labels that each got.

#569 refactor memory management
  include/knowhere/dataset.h
  include/knowhere/index/index_node.h
  include/knowhere/range_util.h
  src/common/comp/brute_force.cc
  src/common/range_util.cc
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  tests/ut/test_range_util.cc
Labels: dco-passed, kind/improvement, approved, lgtm, size/L

#674 remove additional metric_type definition from diskann_config
  src/index/diskann/diskann_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#677 [fix] serialize on empty index
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#676 a theoretical fix for binary data type
  src/index/flat/flat.cc
  src/index/ivf/ivf.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#681 Fix uneven loading of gpu memory when use multi device
  src/common/raft/integration/raft_knowhere_index.cuh
  src/index/gpu_raft/gpu_raft.h
Labels: kind/enhancement, dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, size/S, lgtm

#684 [skip ci] Update cardinal version
  cmake/libs/libcardinal.cmake
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS, do-not-merge/description-tag-conflict

#689 fix possible memory leak caused by iterator
  src/index/hnsw/hnsw.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#694 fix diskann range_search config: search_list_size should for_range_search
  src/index/diskann/diskann_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#688 Add bm25 metric type to inverted index/wand
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index/index_node.h
  include/knowhere/sparse_utils.h
  src/common/comp/brute_force.cc
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_iterator.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XL, kind/feature

#698 Add support mmap index interface
  include/knowhere/comp/knowhere_check.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#700 range_search will early terminate with range_search_k
  include/knowhere/config.h
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#705 fix: correctly compares the size_t and int32_t
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#704 allow empty sparse row
  src/index/sparse/sparse_inverted_index.h
  tests/ut/test_sparse.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#706 add a new meta: range_search_k for range_search
  include/knowhere/comp/index_param.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#707 fix ut typo
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#697 fix: [cherry-pick]Replace gettid() with syscall(SYS_gettid)
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#711 fix knowhere-hnsw filter strategy
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#703 Fix a super-old weird bug in `sq_get_distance_computer_avx512()`
  thirdparty/faiss/faiss/impl/ScalarQuantizerDC_avx512.cpp
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#712 cardinal range_search use the same latency metric as knowhere
  include/knowhere/prometheus_client.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#717 [improvement] Add more cardinal index metrics
  cmake/libs/libcardinal.cmake
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#718 upgrade binary version to support mv_only
  include/knowhere/version.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#721 fix: use std::vector::reserve to correctly initialize vals
  src/index/sparse/sparse_inverted_index.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#727 [skip ci] Update benchmark to test multi data type
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_knowhere.h
Labels: dco-passed, ci-passed, approved, lgtm, size/L

#723 simd support for fp16/bf16
  cmake/libs/libfaiss.cmake
  include/knowhere/operands.h
  python/knowhere/knowhere.i
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
  src/simd/simd_util.h
  tests/ut/test_simd.cc
  thirdparty/DiskANN/src/distance.cpp
  thirdparty/hnswlib/hnswlib/space_cosine.h
  thirdparty/hnswlib/hnswlib/space_ip.h
  thirdparty/hnswlib/hnswlib/space_l2.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#730 [for poc 2024.7.25] Pick range search
  cmake/libs/libcardinal.cmake
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index/index_node.h
  src/index/diskann/diskann_config.h
  tests/ut/test_diskann.cc
Labels: size/M, lgtm

#732 enhance: add filter and search strategy metrics
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, size/M, lgtm

#731 Prerequisites for FAISS HNSW
  thirdparty/faiss/faiss/IndexFlat.h
  thirdparty/faiss/faiss/IndexHNSW.cpp
  thirdparty/faiss/faiss/IndexHNSW.h
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/impl/HNSW.cpp
  thirdparty/faiss/faiss/impl/HNSW.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
  thirdparty/faiss/faiss/impl/code_distance/code_distance-avx512.h
  thirdparty/faiss/faiss/impl/code_distance/code_distance_avx512.h
  thirdparty/faiss/faiss/utils/Heap.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#736 fix cagra cpu search bug
  src/index/gpu_raft/gpu_raft_cagra.cc
Labels: dco-passed, ci-passed, approved, size/S, lgtm, kind/bug

#734 Fix possible asan in unit tests
  tests/ut/test_cluster.cc
  tests/ut/test_diskann.cc
  tests/ut/test_feder.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_iterator.cc
  tests/ut/test_ivfflat_cc.cc
  tests/ut/test_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#741 fix openblas thread version ivf build performance degradation
  include/knowhere/comp/thread_pool.h
Labels: dco-passed, approved, size/S, lgtm, kind/bug

#735 a tweak: better memory management for hnsw
  src/index/hnsw/hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS
