Repository zilliztech/knowhere, pull requests merged in 2025-03, with the labels that each got.

#1101 Add benchmark_simd_qps
  benchmark/CMakeLists.txt
  benchmark/hdf5/benchmark_simd_qps.cpp
  benchmark/hdf5/ref_logs/Makefile
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1104 Add neon implementation for Int8Vector
  src/simd/distances_neon.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#1109 Correct some distance APIs' input parameter types
  thirdparty/faiss/faiss/utils/distances_if.h
  thirdparty/faiss/faiss/utils/half_precision_floating_point_distances.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1110 Rename half_precision_floating_point_xxx to xxx_typed for better readability
  src/common/comp/brute_force.cc
  thirdparty/faiss/faiss/utils/distances.h
  thirdparty/faiss/faiss/utils/distances_typed.cpp
  thirdparty/faiss/faiss/utils/distances_typed.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1114 BruteForce support Int8Vector
  benchmark/hdf5/benchmark_float.cpp
  include/knowhere/operands.h
  python/knowhere/__init__.py
  python/knowhere/knowhere.i
  src/common/comp/brute_force.cc
  tests/ut/test_bruteforce.cc
  thirdparty/faiss/faiss/utils/distances_if.h
  thirdparty/faiss/faiss/utils/distances_typed.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1108 Fix CAGRA-HNSW serialization format
  src/common/cuvs/proto/cuvs_index.cuh
  tests/ut/test_gpu_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1116 [bug] fix IVFPQFastScan::RangeSearch() on ARM
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1120 fix ARM bf16 patch functions
  src/simd/distances_neon.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1126 enhance: reduce the queuing problem caused by the mixed task of growing index and sealed index
  include/knowhere/comp/thread_pool.h
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  include/knowhere/index/index_node_thread_pool_wrapper.h
  src/index/data_view_dense_index/data_view_dense_index.h
  src/index/data_view_dense_index/index_node_with_data_view_refiner.h
  src/index/diskann/diskann.cc
  src/index/flat/flat.cc
  src/index/gpu/flat_gpu/flat_gpu.cc
  src/index/gpu/ivf_gpu/ivf_gpu.cc
  src/index/gpu_cuvs/gpu_cuvs.h
  src/index/gpu_cuvs/gpu_cuvs_cagra.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.h
  src/index/index.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_data_view_index.cc
  tests/ut/test_index_node.cc
  tests/ut/test_ivfflat_cc.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1128 fix: add use_knowhere_build_pool param for BuildAsync
  include/knowhere/index/index_node.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS
