Repository zilliztech/knowhere, pull requests merged in 2025-09, with the labels that each got.

#1330 feat: extend emb_list index to support HNSW_SQ, HNSW_PQ, and HNSW_PRQ
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index/index_table.h
  src/index/emb_list/emb_list_config.h
  src/index/emb_list/emb_list_hnsw.cc
  src/index/hnsw/faiss_hnsw.cc
  tests/ut/test_emb_list_hnsw.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1336 enhance: opt minhash bf search
  src/common/comp/brute_force.cc
  src/index/minhash/minhash_index_node.cc
  src/index/minhash/minhash_lsh.h
  src/index/minhash/minhash_util.cc
  src/index/minhash/minhash_util.h
  src/simd/distances_avx512.cc
  src/simd/distances_ref.cc
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_minhash_index.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/XL

#1339 [2.5][cherry-pick] MinHash: opt bf search and fix some bugs
  src/common/comp/brute_force.cc
  src/index/minhash/minhash_index_node.cc
  src/index/minhash/minhash_lsh.h
  src/index/minhash/minhash_util.cc
  src/index/minhash/minhash_util.h
  src/simd/distances_avx512.cc
  src/simd/distances_ref.cc
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_minhash_index.cc
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1341 enhance: Remove the Restriction of dim % bands == 0 in MinHash LSH
  src/common/comp/brute_force.cc
  src/index/minhash/minhash_lsh.h
  src/index/minhash/minhash_util.cc
  src/index/minhash/minhash_util.h
  tests/ut/test_minhash_index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1346 enhance: Add search op context
  cmake/libs/cardinal/v1/CMakeLists.txt
  cmake/libs/cardinal/v2/CMakeLists.txt
  cmake/libs/libmilvus-common.cmake
  include/knowhere/comp/brute_force.h
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  include/knowhere/index/index_node_thread_pool_wrapper.h
  src/common/comp/brute_force.cc
  src/index/data_view_dense_index/index_node_with_data_view_refiner.h
  src/index/diskann/diskann.cc
  src/index/diskann/diskann_aisaq.cc
  src/index/emb_list/emb_list_hnsw.cc
  src/index/flat/flat.cc
  src/index/gpu_cuvs/gpu_cuvs.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.h
  src/index/index.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/index_node_thread_pool_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/minhash/minhash_index_node.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_index_node.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1348 Add iterator test for tiered index
  tests/ut/test_iterator.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1347 hnsw binary support
  src/index/hnsw/faiss_hnsw.cc
  tests/ut/test_get_vector.cc
  tests/ut/test_search.cc
  thirdparty/faiss/faiss/FaissHook.cpp
  thirdparty/faiss/faiss/FaissHook.h
  thirdparty/faiss/faiss/IndexScalarQuantizer.cpp
  thirdparty/faiss/faiss/MetricType.h
  thirdparty/faiss/faiss/impl/ScalarQuantizer.cpp
  thirdparty/faiss/faiss/impl/ScalarQuantizer.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_avx512.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerCodec_neon.h
  thirdparty/faiss/faiss/impl/ScalarQuantizerDC.cpp
  thirdparty/faiss/faiss/impl/ScalarQuantizerDC.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
