Repository zilliztech/knowhere, pull requests merged in 2025-07, with the labels that each got.

#1236 fix: fix gpu image compile
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1240 feat(simd/rvv): add RVV SIMD optimization for int8_vec_inner_product, int8_vec_L2sqr, int8_vec_norm_L2sqr
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1244  [SIMD][RVV] add RVV SIMD optimization for bf16_vec_inner_product_rvv && bf16_vec_L2sqr_rvv && bf16_vec_norm_L2sqr_rvv
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1246 fix: sparse vector dup key error in bruteforce range search
  src/common/comp/brute_force.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1251 fix: sparse: all entries should use span in version 8
  include/knowhere/version.h
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, kind/improvement, approved, size/M, lgtm

#1248 [SIMD][RVV] add RVV SIMD optimization for bf16_vec_inner_product_batch_4_rvv && bf16_vec_L2sqr_batch_4_rvv
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1253 feat(simd-rvv): Add RVV SIMD optimized bf16 patch functions for inner product and L2sqr
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1259 feat(simd-rvv): Add RVV SIMD optimized batch-4 bf16 patch functions
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1260 unify bf search and search_with_buf
  src/common/comp/brute_force.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1265 fix: sparse vector dup key error in bruteforce range search (#1246)
  src/common/comp/brute_force.cc
Labels: dco-passed, ci-passed, approved, size/S, lgtm

#1274 Fix ARM duplicate definitions of ivec_inner_product and ivec_L2sqr in hook.cc
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1278 [2.5][cherry-pick]update fvec_L2sqr_ny_nearest function in arm machine
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L
