Repository zilliztech/knowhere, pull requests merged in 2025-01, with the labels that each got.

#1008 Use search_pool to control iterator->Next()
  include/knowhere/comp/brute_force.h
  include/knowhere/expected.h
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  include/knowhere/index/index_node_data_mock_wrapper.h
  src/common/comp/brute_force.cc
  src/index/diskann/diskann.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/hnsw.h
  src/index/index.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/ivf/ivf.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_index_node.cc
Labels: kind/enhancement, dco-passed, ci-passed, approved, lgtm, size/XL

#1011 memory usage optimization for sparse vector
  CMakeLists.txt
  include/knowhere/sparse_utils.h
  python/setup.py
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_sparse.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL

#1017 sparse: accelerate the writing of index files
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1018 sparse: add max score ratio downscaling for approximate searching
  src/index/sparse/sparse_inverted_index_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1022 sparse: readd GetVectorByIds support for growing segments with IP metric
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_sparse.cc
Labels: kind/enhancement, dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L, do-not-merge/description-tag-conflict

#1021 fix: make default buckets more accurate
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1024 enhance: update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1015 add DAAT MaxScore support for sparse vector
  include/knowhere/comp/index_param.h
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1020 Support MV only for HNSW
  include/knowhere/bitsetview.h
  include/knowhere/bitsetview_idselector.h
  include/knowhere/comp/index_param.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/hnsw/impl/IndexBruteForceWrapper.cc
  src/index/hnsw/impl/IndexConditionalWrapper.cc
  src/index/hnsw/impl/IndexHNSWWrapper.cc
  tests/ut/test_faiss_hnsw.cc
  tests/ut/test_index_check.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
  thirdparty/faiss/faiss/index_io.h
Labels: dco-passed, ci-passed, approved, lgtm, kind/feature, size/XXL

#1027 Fix knowhere build
  src/index/hnsw/faiss_hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1033 sparse: disable refinement by default
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1038 Clean benchmark build warnings
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1040 Show UT case runtime
  scripts/run_codecov.sh
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1037 Mock register VECTOR_INT8 for all index types
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  src/index/flat/flat.cc
  src/index/hnsw/faiss_hnsw.cc
  src/index/index_node_data_mock_wrapper.cc
  src/index/ivf/ivf.cc
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1029 sparse: refactor approx dimension max score ratio
  include/knowhere/comp/index_param.h
  include/knowhere/sparse_utils.h
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
  src/index/sparse/sparse_inverted_index_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1041 sparse: reduce ut execution time
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1036 Add IsAdditionalScalarSupported check for mv_only
  include/knowhere/index/index.h
  include/knowhere/index/index_node.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/index.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1044 Update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1045 Update diskann mv UT
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm
