Repository zilliztech/knowhere, pull requests merged in 2025-02, with the labels that each got.

#1050 sparse: early return to avoid mmapping empty file
  src/index/sparse/sparse_inverted_index.h
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1053 [skip e2e] update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1054 [skip e2e] Optimize load hdf5 template APIs
  benchmark/hdf5/benchmark_binary.cpp
  benchmark/hdf5/benchmark_binary_range.cpp
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  benchmark/hdf5/benchmark_hdf5.h
  benchmark/hdf5/gen_fbin_file.cpp
  benchmark/hdf5/gen_hdf5_file.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1048 Migration from RAFT to cuVS
  CMakeLists.txt
  README.md
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/ref_logs/Makefile
  ci/E2E_GPU.groovy
  ci/UT_GPU.groovy
  ci/docker/builder/gpu/ubuntu20.04/Dockerfile
  ci/docker/builder/gpu/ubuntu22.04/Dockerfile
  cmake/libs/libcuvs.cmake
  cmake/libs/librapids.cmake
  cmake/libs/librmm.cmake
  cmake/utils/compile_flags.cmake
  conanfile.py
  include/knowhere/comp/index_param.h
  include/knowhere/expected.h
  src/common/comp/knowhere_config.cc
  src/common/config.cc
  src/common/cuvs/integration/brute_force_index.cu
  src/common/cuvs/integration/cagra_index.cu
  src/common/cuvs/integration/cuvs_knowhere_config.hpp
  src/common/cuvs/integration/cuvs_knowhere_index.cuh
  src/common/cuvs/integration/cuvs_knowhere_index.hpp
  src/common/cuvs/integration/ivf_flat_index.cu
  src/common/cuvs/integration/ivf_pq_index.cu
  src/common/cuvs/integration/raft_initialization.cc
  src/common/cuvs/integration/raft_initialization.hpp
  src/common/cuvs/integration/type_mappers.hpp
  src/common/cuvs/proto/cuvs_index.cuh
  src/common/cuvs/proto/cuvs_index_kind.hpp
  src/common/raft/integration/cagra_index.cu
  src/common/raft/integration/cagra_instantiations.cu
  src/common/raft/integration/ivf_flat_index.cu
  src/common/raft/integration/ivf_flat_instantiations.cu
  src/common/raft/integration/ivf_pq_index.cu
  src/common/raft/integration/ivf_pq_instantiations.cu
  src/common/raft/proto/filtered_search_instantiation.cuh
  src/common/raft/proto/raft_index.cuh
  src/index/gpu/gpu_res_mgr.h
  src/index/gpu_cuvs/gpu_cuvs.h
  src/index/gpu_cuvs/gpu_cuvs_brute_force.cc
  src/index/gpu_cuvs/gpu_cuvs_brute_force_config.h
  src/index/gpu_cuvs/gpu_cuvs_cagra.cc
  src/index/gpu_cuvs/gpu_cuvs_cagra_config.h
  src/index/gpu_cuvs/gpu_cuvs_ivf_flat.cc
  src/index/gpu_cuvs/gpu_cuvs_ivf_flat_config.h
  src/index/gpu_cuvs/gpu_cuvs_ivf_pq.cc
  src/index/gpu_cuvs/gpu_cuvs_ivf_pq_config.h
  src/index/index_factory.cc
  tests/ut/test_config.cc
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_check.cc
  tests/ut/test_knowhere_init.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1052 Reduce the pq build time
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/hook.cc
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1016 enhance: knowhere support data view index node
  include/knowhere/comp/index_param.h
  include/knowhere/comp/rw_lock.h
  include/knowhere/index/index_node.h
  include/knowhere/object.h
  include/knowhere/operands.h
  include/knowhere/utils.h
  src/common/utils.cc
  src/index/data_view_dense_index/data_view_dense_index.h
  src/index/data_view_dense_index/data_view_index_config.h
  src/index/data_view_dense_index/index_node_with_data_view_refiner.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  tests/ut/test_data_view_index.cc
  tests/ut/test_iterator.cc
  tests/ut/test_utils.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexRefine.cpp
  thirdparty/faiss/faiss/utils/Heap.cpp
  thirdparty/faiss/faiss/utils/Heap.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1059 Disable VECTOR_INT8 for all index types except HNSW
  include/knowhere/index/index_table.h
  tests/ut/test_index_check.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1060 [skip e2e] Optimize benchmark
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_knowhere.h
Labels: dco-passed, kind/improvement, approved, size/M, lgtm

#1062 enhence: optimize cmake for milvus lite
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1066 fix: fvec_L2sqr_ny_nearest_avx bad memory access
  src/simd/distances_avx.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1056 Add Hamming distance to cuvs CAGRA
  include/knowhere/index/index_table.h
  src/common/cuvs/integration/brute_force_index.cu
  src/common/cuvs/integration/cagra_index.cu
  src/common/cuvs/integration/cuvs_knowhere_index.cuh
  src/common/cuvs/integration/cuvs_knowhere_index.hpp
  src/common/cuvs/integration/ivf_flat_index.cu
  src/common/cuvs/integration/ivf_pq_index.cu
  src/common/cuvs/integration/type_mappers.hpp
  src/common/cuvs/proto/cuvs_index.cuh
  src/index/gpu_cuvs/gpu_cuvs.h
  src/index/gpu_cuvs/gpu_cuvs_cagra.cc
  src/index/gpu_cuvs/gpu_cuvs_cagra_config.h
  tests/ut/test_gpu_search.cc
  tests/ut/test_index_check.cc
  tests/ut/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1077 sparse: make bm25 avgdl support value smaller than 1
  include/knowhere/config.h
  src/common/comp/brute_force.cc
  src/index/sparse/sparse_index_node.cc
  src/index/sparse/sparse_inverted_index.h
Labels: dco-passed, ci-passed, approved, lgtm, size/XS, kind/bug

#1082 Clean knowhere build warnings
  benchmark/hdf5/gen_fbin_file.cpp
  cmake/utils/compile_flags.cmake
  include/knowhere/comp/knowhere_check.h
  include/knowhere/utils.h
  src/simd/distances_avx.cc
  src/simd/distances_avx512.cc
  src/simd/distances_neon.cc
  src/simd/distances_sse.cc
  src/simd/simd_util.h
  tests/ut/test_data_view_index.cc
  tests/ut/test_index_node.cc
  thirdparty/faiss/faiss/impl/ResultHandler.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1079 fix github mergify rule
  .github/mergify.yml
Labels: dco-passed, ci-passed, approved, size/M, lgtm, kind/bug

#1088 Format simd APIs for better readability
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1090 Tiny opts for simd APIs
  ci/E2E-arm.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_powerpc.cc
  src/simd/distances_powerpc.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1094 Fix pyknowhere build fail
  ci/E2E-arm.groovy
  ci/E2E2-SSE.groovy
  ci/E2E2.groovy
  ci/E2E_GPU.groovy
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1096 Optimize test_simd
  src/simd/hook.cc
  tests/ut/test_simd.cc
Labels: dco-passed, do-not-merge/missing-related-issue, ci-passed, approved, lgtm, size/L

#1097 Fix swig build fail
  .github/workflows/ut.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1098 Add Int8Vector SIMD APIs for avx512/avx2/sse/ref
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_neon.cc
  src/simd/distances_neon.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL
