Repository zilliztech/knowhere, pull requests merged in 2025-08, with the labels that each got.

#1284 feat: Add RISC-V Vector Extension optimization for fvec_L2sqr_ny_transposed
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1298 fix whines of GCC-15 in AISAQ
  thirdparty/DiskANN/include/diskann/utils.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1292 support deserializing CAGRA index from GPU format to CPU format
  src/index/gpu_cuvs/gpu_cuvs_cagra.cc
  src/index/gpu_cuvs/gpu_cuvs_cagra_config.h
  tests/ut/test_gpu_search.cc
  thirdparty/hnswlib/hnswlib/hnswalg.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1303 Fix benchmarks. Fix the compilation using clang.
  benchmark/hdf5/benchmark_float.cpp
  benchmark/hdf5/benchmark_float_bitset.cpp
  benchmark/hdf5/benchmark_float_qps.cpp
  benchmark/hdf5/benchmark_float_range.cpp
  benchmark/hdf5/benchmark_float_range_bitset.cpp
  thirdparty/DiskANN/src/aux_utils.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1314 fix: Fix tests failures caused by config type changes
  src/common/config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1312 fix: fix binary search crash in minhash_lsh index
  src/index/minhash/minhash_index_node.cc
  src/index/minhash/minhash_lsh.h
  src/simd/distances_avx512.cc
  tests/ut/test_simd.cc
Labels: dco-passed, ci-passed, approved, lgtm, size/L

#1321 fix ccache path
  .github/actions/cache-restore/action.yaml
  .github/actions/cache-save/action.yaml
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1313 Support fetch pool for remote storage
  cmake/libs/libmilvus-common.cmake
  include/knowhere/comp/knowhere_config.h
  src/common/comp/knowhere_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1324 fix cardinal link
  CMakeLists.txt
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1326 enhance: add int8 fallback
  src/index/hnsw/faiss_hnsw.cc
  tests/ut/test_diskann.cc
  tests/ut/test_get_vector.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1328 enhance: enable hnsw int8 iterator support
  src/index/hnsw/faiss_hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1319 feat: extend emb_list metric support for both cosine and ip
  include/knowhere/comp/index_param.h
  include/knowhere/emb_list_utils.h
  src/common/comp/brute_force.cc
  src/index/emb_list/emb_list_hnsw.cc
  tests/ut/test_emb_list_hnsw.cc
  thirdparty/faiss/faiss/utils/distances.cpp
  thirdparty/faiss/faiss/utils/distances.h
  thirdparty/faiss/faiss/utils/distances_typed.cpp
  thirdparty/faiss/faiss/utils/distances_typed.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1333 Bump milvus-common version
  cmake/libs/libmilvus-common.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS
