Repository zilliztech/knowhere, pull requests merged in 2025-05, with the labels that each got.

#1179 Fix scann filter search performance and cleanup ensure_topk_full config
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  thirdparty/faiss/faiss/impl/pq4_fast_scan_search_1.cpp
  thirdparty/faiss/faiss/impl/pq4_fast_scan_search_qbs.cpp
  thirdparty/faiss/faiss/impl/simd_result_handlers.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1186 fix: optimize boolean config parsing in json
  src/common/config.cc
  tests/ut/test_config.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1190 fix a problem of incorrect VPOPCNTDQ instruction set detection
  src/simd/instruction_set.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1188 sparse: add StaticHasRawData support
  src/index/index_static.cc
  src/index/sparse/sparse_index_node.cc
  tests/ut/test_index_check.cc
  tests/ut/test_sparse.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1198 fix: optimize the output log of the refine type
  src/index/hnsw/faiss_hnsw_config.h
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1206 [skip e2e]: update cardinal version
  cmake/libs/libcardinal.cmake
  cmake/libs/libfaiss.cmake
  conanfile.py
  include/knowhere/comp/bloomfilter.h
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/common/metric.h
  src/common/utils.cc
  src/index/minhash/minhash_index_config.h
  src/index/minhash/minhash_index_node.cc
  src/index/minhash/minhash_lsh.h
  src/index/minhash/minhash_util.cc
  src/index/minhash/minhash_util.h
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_diskann.cc
  tests/ut/test_minhash_index.cc
  tests/ut/test_simd.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/MetricType.h
  thirdparty/faiss/faiss/impl/io.cpp
  thirdparty/faiss/faiss/impl/io.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL
