Repository zilliztech/knowhere, pull requests merged in 2025-06, with the labels that each got.

#1207 enhance: knowhere support metric mhjaccard and index minhash lsh for minhash vector
  cmake/libs/libfaiss.cmake
  conanfile.py
  include/knowhere/comp/bloomfilter.h
  include/knowhere/comp/index_param.h
  include/knowhere/config.h
  include/knowhere/index/index_factory.h
  include/knowhere/index/index_table.h
  include/knowhere/utils.h
  src/common/comp/brute_force.cc
  src/common/metric.h
  src/common/utils.cc
  src/index/minhash/minhash_index_node.cc
  src/index/minhash/minhash_lsh.h
  src/index/minhash/minhash_lsh_config.h
  src/index/minhash/minhash_util.cc
  src/index/minhash/minhash_util.h
  src/simd/distances_avx.cc
  src/simd/distances_avx.h
  src/simd/distances_avx512.cc
  src/simd/distances_avx512.h
  src/simd/distances_ref.cc
  src/simd/distances_ref.h
  src/simd/distances_sse.cc
  src/simd/distances_sse.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_diskann.cc
  tests/ut/test_minhash_index.cc
  tests/ut/test_simd.cc
  tests/ut/utils.h
  thirdparty/faiss/faiss/MetricType.h
  thirdparty/faiss/faiss/impl/io.cpp
  thirdparty/faiss/faiss/impl/io.h
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XXL

#1209 Enable SVE Support for L2 Metric Computation in INT8 functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1211 use iterator-based rangesearch if support ann_iterator (ivf)
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1212 Enable SVE Support for L2 Metric Computation in BF16 functions
  cmake/libs/libfaiss.cmake
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1218 Enable SVE Support for IP Metric Computation in INT8 functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1216 Rvv optimization for Distances
  cmake/libs/libfaiss.cmake
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1221 Enable SVE Support for IP Metric Computation in BF16 functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1220 feat: add RVV SIMD versions of fvec_L2sqr, fvec_L1, and fvec_Linf
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1223 feat(simd): add RVV-optimized vector operations
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1227 Fix SCANN iterator problem on Cosine
  thirdparty/faiss/faiss/IndexIVFFastScan.cpp
  thirdparty/faiss/faiss/IndexIVFFastScan.h
  thirdparty/faiss/faiss/IndexScaNN.cpp
  thirdparty/faiss/faiss/impl/index_read.cpp
  thirdparty/faiss/faiss/impl/index_write.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1232 [SIMD][RVV] Optimize int8 distance functions: ivec_inner_product_rvv & ivec_L2sqr_rvv with RVV SIMD
  src/simd/distances_rvv.cc
  src/simd/distances_rvv.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm
