Repository zilliztech/knowhere, pull requests merged in 2025-04, with the labels that each got.

#1129 [skip e2e]: update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#969 Enable SVE Support for L2 Metric Computation in FP32
  cmake/libs/libfaiss.cmake
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
  src/simd/hook.h
  tests/ut/test_knowhere_init.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/L

#1139 Add search level metric
  include/knowhere/prometheus_client.h
  src/common/prometheus_client.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1141 fix: fix gpu build
  include/knowhere/index/index_node.h
  src/index/gpu_cuvs/gpu_cuvs_cagra.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1134 Enable SVE Support for L2 Metric Computation in FP16 and NY functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1148 Add fallback bf for hnsw when the result is not enough
  src/index/hnsw/faiss_hnsw.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1150 fix : add the compatibility logic of mmap and sve on macos platform
  cmake/libs/libfaiss.cmake
  src/simd/hook.cc
  thirdparty/faiss/faiss/impl/mapped_io.cpp
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1154 fix: update ubuntu version in ci test
  .github/workflows/analyzer.yaml
  .github/workflows/pre-commit.yml
  .github/workflows/release-python.yml
  .github/workflows/release.yaml
  src/common/comp/brute_force.cc
  src/index/index_static.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1153 enhance: add maximum version
  include/knowhere/version.h
  tests/ut/test_utils.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1160 knowhere support riscv
  cmake/libs/libfaiss.cmake
  cmake/utils/platform_check.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1155 enhance: add simde package
  conanfile.py
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1146 Enable SVE Support for IP Metric Computation in FP32 functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/S, lgtm

#1169 [skip e2e]: update cardinal version
  cmake/libs/libcardinal.cmake
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XS

#1167 Enable SVE Support for IP Metric Computation in FP16 and NY functions
  src/simd/distances_sve.cc
  src/simd/distances_sve.h
  src/simd/hook.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, size/M, lgtm

#1162 Add refine for RaBitQ
  include/knowhere/index/index_table.h
  src/index/hnsw/faiss_hnsw.cc
  src/index/ivf/ivf.cc
  src/index/ivf/ivf_config.h
  src/index/ivf/ivfrbq_wrapper.cc
  src/index/ivf/ivfrbq_wrapper.h
  src/index/refine/refine_utils.cc
  src/index/refine/refine_utils.h
  tests/ut/test_get_vector.cc
  tests/ut/test_iterator.cc
  tests/ut/test_search.cc
Labels: dco-passed, ci-passed, kind/improvement, approved, lgtm, size/XL
